<div id="modal-create-form-main" style="display: none">
    <div class="page-title">
        <h1>Регистрация</h1>
    </div>
    <?php
    ?>
    <form  title="<?php echo Mage::getUrl('customer/account/createCustomer')?>"  method="post" id="form-validate-create" onsubmit="ModalFormCreate(this); return false;">
        <input
            type="text"
            name="firstname"
            id="firstnameLastname"
            placeholder="Введите Имя И Фамилию<?php //echo $this->__('Name') ?>"
            class="input-text required-entry validate-formCreateModalFirstLast"
            />

        <input type="email"
               name="email"
               id="emailReg"
               placeholder="Введите email<?php //echo $this->__('Email') ?>"
               class="input-text required-entry validate-email validate-formCreateModalEm"
            />

        <?php if ($this->isNewsletterEnabled()): ?>
            <div class="checkBoxBlock">
                <input type="checkbox" name="is_subscribed"
                       title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1"
                       id="is_subscribed" checked="checked"/>
                <label><?php echo $this->__('Sign Up for Newsletter') ?></label>
            </div>

        <?php endif ?>

        <input type="password"
               name="password"
               id="password"
               placeholder="Введите пароль<?php //echo $this->__('Password') ?>"
               class="input-text required-entry validate-password"
            />
        <input type="password"
               name="confirmation"
               id="confirmation"
               placeholder="<?php echo $this->__('Confirm Password') ?>"
               class="input-text required-entry validate-cpassword"
            />

        <button type="submit" title="<?php echo $this->__('Submit') ?>">
            Регистрация
            <?php //echo $this->__('Submit') ?>
        </button>

    </form>
    <div class="modal-login-footer">
        <a title="<?php echo $this->__('Авторизация') ?>" onclick="CreateAccountHide();">
            <h3><?php echo $this->__('Авторизация') ?></h3></a>
    </div>
</div>

