<div id="modal-create-form-main" style="display: none">
    <h1>Регистрация</h1>
    <?php
    ?>
    <form  title="<?php echo Mage::getUrl('customer/account/createCustomer')?>"  method="post" id="form-validate-create" onsubmit="ModalFormCreate(this); return false;">
        <input
            type="text"
            name="firstname"
            id="firstname"
            placeholder="<?php echo $this->__('Name') ?>"
            class="input-text required-entry validate-data"
            >
        <input type="text"
               name="lastname"
               id="lastname"
               placeholder="<?php echo $this->__('Family') ?>"
               class="input-text required-entry validate-data"
            >
        <input type="email"
               name="email"
               id="emailReg"
               placeholder="<?php echo $this->__('Email') ?>"
               class="input-text required-entry validate-email validate-formCreateModal"
            >

        <?php if ($this->isNewsletterEnabled()): ?>
            <div>
                <input type="checkbox" name="is_subscribed"
                       title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1"
                       id="is_subscribed"<?php if ($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> />
                <label><?php echo $this->__('Sign Up for Newsletter') ?></label>
            </div>

        <?php endif ?>

        <input type="password"
               name="password"
               id="password"
               placeholder="<?php echo $this->__('Password') ?>"
               class="input-text required-entry validate-password"
            >
        <input type="password"
               name="confirmation"
               id="confirmation"
               placeholder="<?php echo $this->__('Confirm Password') ?>"
               class="input-text required-entry validate-cpassword"
            >

        <button type="submit" title="<?php echo $this->__('Submit') ?>">
            <?php echo $this->__('Submit') ?>
        </button>

    </form>
    <div class="modal-login-footer">
        <a title="<?php echo $this->__('Login an Account') ?>" onclick="CreateAccountHide();">
            <h3><?php echo $this->__('Login an Account') ?></h3></a>
    </div>
</div>