<div id="modal-forgot-password-form" style="display: none">
    <div class="page-title">
        <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
    </div>

    <form title="<?php echo Mage::getUrl('customer/account/forgotPasswordPostAjax') ?>" method="post" id="modal-forgot-password-form-form" onsubmit="ForgotPassword(this); return false;">
        <div>
            <p class="message" id="ok_message"><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
            <input type="text" name="email" alt="email" id="email_address" class="validate-ForgotPasswordModal input-text required-entry validate-email" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" placeholder="Enter Email"/>
        </div>
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><?php echo $this->__('Submit') ?></button>
    </form>

    <div class="modal-login-footer">
        <a title="<?php echo $this->__('Login') ?>" onclick="ForgotPasswordHide();">
            <h3><?php echo $this->__('Login') ?></h3></a>
    </div>
</div>