
    <div class="aling-central-modal mainWindow">

        <div id="oblogka" class="mainWindow aling-central-modal" style="display: none; width: 97%;height: 510px; z-index:20000; position: absolute;margin-right: auto; margin-left: auto">
            <i class="fa fa-spinner fa-pulse fa-4x" style="margin-top: 45%; color: #000000"></i>
        </div>
        <div style="width: 100%; height: 500px; z-index:10000; position: absolute">
            <?php
            echo $this->getChild('login.form')->toHtml();
            echo $this->getChild('create.form')->toHtml();
            echo $this->getChild('forgot.form')->toHtml();
            ?>
        </div>

    </div>

