<?php
/* @var $this Webinse_OAuth_Block_OauthData */
?>
<div class="SocialBlock">
    <h2><?php echo $this->__('Enter with')?></h2>
    <div class="SocialBlockBlock">
        <?php if (count($this->getArraySocialNetwork()) > 0): ?>
            <?php foreach($this->getArraySocialNetwork() as $soc => $val):?>
                <a href="<?php echo $val?>" class="blockSocialIcon">
                    <i class="<?php echo $this->getIconClass($soc)?>"></i>
                </a>
            <?php endforeach;?>
        <?php endif;?>
    </div>
</div>