<?php
/*
 * @category    Webinse
 * @package     Webinse_All
 * @author      Dmitriy Perederiy <perederiy1993@yandex.ua>
 */
?>

<?php if (!Mage::helper('core/cookie')->isUserNotAllowSaveCookie()): ?>
    <?php $accountId = Mage::getStoreConfig(Mage_GoogleAnalytics_Helper_Data::XML_PATH_ACCOUNT) ?>
    <!-- BEGIN Universal Analytics CODEs -->
    <script type="text/javascript">

          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          <?php echo $this->_getPageTrackingCode($accountId) ?>
          <?php echo $this->_getOrdersTrackingCode() ?>

    </script>
    <!-- END Universal Analytics CODE -->
<?php endif; ?>