

<ul>
    <li>
        <div class="Trotsky">
            Смотреть ещё:
        </div>
    </li>
    <li>
        <div class="Trotsky">
            <a>ссылка 1</a>
        </div>
    </li>
    <li>
        <div class="Trotsky">
            <a>ссылка 2</a>
        </div>
    </li>
    <li>
        <div class="Trotsky">
            <a>ссылка 3</a>
        </div>
    </li>
</ul>






<?php
require_once Mage::getBaseDir().'/kap_trotsky/lib/Model.php' ;
$kap = new KapModel();
echo $kap->getLinks();
?>