

<ul style="margin-top: 10px">
    <li>
        <div class="Trotsky TrotskyHead">
            Смотрите также:
        </div>
    </li>
    <li>
        <div class="Trotsky">
            <a>Cсылка 1</a>
        </div>
    </li>
    <li>
        <div class="Trotsky">
            <a>Cсылка 2</a>
        </div>
    </li>
    <li>
        <div class="Trotsky">
            <a>Cсылка 3</a>
        </div>
    </li>
</ul>






<?php

require_once Mage::getBaseDir().'/kap_trotsky/lib/Model.php' ;
$kap = new KapModel();
echo $kap->getLinks();

?>