<?php
$products = $this->getProducts();

$columnNumber = $this->getColumnNumber();
$colunnSize = $this->getColumnSize();
$featuredWidth = 0;
$size = 0;
if ($this->hasFeaturedProducts()) {
    $columnNumber = $columnNumber - 1;
    $featuredWidth = 220 + 10;
    $featuredProducts = $this->getFeaturedProducts();
}elseif($this->hasFeaturedCategories()) {
    $columnNumber = $columnNumber - 1;
    $featuredWidth = 220 + 10;
    $featuredCategories = $this->getFeaturedCategories();
}
if(count($products) < $columnNumber){
    $columnNumber = count($products);
}
if($columnNumber != 0){
if(count($products) % $columnNumber == 0)
    $line = count($products)/$columnNumber;
else
    $line = ceil(count($products)/$columnNumber);
$size = '0';
if ($columnNumber && $colunnSize){
        $size = floatval($columnNumber * ($colunnSize + 10) + 20 + $featuredWidth + 5 + $this->getCustomStyle('border_size')*($columnNumber + 2));
}
$i=0;
$j = 0;
$col = 1;
$colAdd = count($products) % $columnNumber;/*number col add more 1 item*/
$itemAdd = floor(count($products)/$columnNumber);/*min item per col*/
}
?>
<?php if (count($products)): ?>
    <div class="products-megamenu-list sub-menu" style="border:<?php echo $this->getCustomStyle('border_size') ?>px solid #<?php echo $this->getCustomStyle('border_color') ?> !important;background:#<?php echo $this->getCustomStyle('background_color') ?> !important;width: <?php echo $size; ?>px !important;" >
        <ul class="level0-megamenu" style="width:<?php echo $size-20;?>px !important">
			<h1 style="color:#<?php echo $this->getCustomStyle('text_color');?>;font-size:<?php echo $this->getCustomStyle('text_font_size');?>px;border-bottom:1px dashed #<?php echo $this->getCustomStyle('border_color')?>;">
                <?php echo $this->getTemplateBlock($this->getHeaderContent()) ?>
            </h1>
            <li class="level1-megamenu" style="width:<?php echo $size - $featuredWidth - 25;?>px !important;<?php if (!$this->hasFeaturedItem()): ?>border-right:none !important<?php endif; ?>">
                <h4 style="color:#<?php echo $this->getCustomStyle('subtitle_color') ?>;font-size:<?php echo $this->getCustomStyle('subtitle_font_size') ?>px;"><?php echo $this->getItem()->getProductsBoxTitle(); ?></h4>                
                <ul class="level2-megamenu" style="width:<?php echo $colunnSize; ?>px !important">
                    <?php foreach ($products as $product): ?>
                        <?php $i++; ?>
                        <?php $j++; ?>
                        <li>
                            <a style="color:#<?php echo $this->getCustomStyle('link_color') ?> !important;font-size:11px !important;" href="<?php echo $product->getProductUrl(); ?>">
                                <span><?php echo $product->getName(); ?></span>
                            </a>
                        </li>	
                        <?php if(($col<=$colAdd && $j==$itemAdd+1)||($col>$colAdd && $j==$itemAdd)):?>
                
                        <?php $col++ ?>
                        <?php if($i==count($products)) break;?>
                        </ul>
                        <ul class="level2-megamenu" style="width:<?php echo $colunnSize; ?>px !important">
                        <?php $j=0 ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            </li>
            <?php $max = 0;?>
            <?php if($this->hasFeaturedProducts() && count($featuredProducts)):?>
            
        <li class="level1-megamenu featured" style="width:220px !important">
                <div class="level1-title">
                    <h2 style="color:#<?php echo $this->getCustomStyle('subtitle_color');?>;font-size:<?php echo $this->getCustomStyle('subtitle_font_size');?>px;">
                        <?php echo $this->__('Featured Products');?>
                    </h2>					
                </div>
                <ul class="level2-megamenu">
                    <?php foreach($featuredProducts as $featuredProduct):?>
                    <?php $max++;?>
                    <li class="product-item">
                        <a class="product-image" href="<?php echo $featuredProduct->getProductUrl();?>">
                            <img title="<?php echo Mage::helper('megamenu')->htmlEscape($featuredProduct->getName());?>"src="<?php echo $this->getImagePath($featuredProduct, 110);?>" width="110"/>
                        </a>
                        <div class="product-shop">
                            <a href="<?php echo $featuredProduct->getProductUrl();?>">
                                <h1 class="product-name"style="font-size:<?php echo $this->getCustomStyle('link_font_size');?>px;color:#<?php echo $this->getCustomStyle('link_color');?>;">
                                    <?php echo $featuredProduct->getName();?>
                                </h1>
                            </a>
                            <?php echo Mage::getBlockSingleton('catalog/product')->setArea('frontend')->getPriceHtml($featuredProduct, true)?>
                            <button class="button" onclick="window.location.href = '<?php echo $featuredProduct->getProductUrl();?>'"><?php echo $this->__('View Detail');?></button>
                        </div>
                    </li>
                    <?php if($max == 2) break;?>
                    <?php endforeach;?>
                </ul>
            </li>
            <?php elseif($this->hasFeaturedCategories() && count($featuredCategories)):?>
            <li class="level1-megamenu featured" style="width:220px !important">
                <div class="level1-title">
                    <h2 style="color:#<?php echo $this->getCustomStyle('subtitle_color');?>;font-size:<?php echo $this->getCustomStyle('subtitle_font_size');?>px;">
                        <?php echo $this->__('Featured Categories');?>
                    </h2>					
                </div>
                <ul class="level2-megamenu">
                    <?php foreach($featuredCategories as $featuredCategory):?>
                    <?php $max++;?>
                    <li class="product-item">
                        <a class="product-image" href="<?php echo $featuredCategory->getUrl();?>">
                            <img title="<?php echo Mage::helper('megamenu')->htmlEscape($featuredCategory->getName());?>"src="<?php echo $featuredCategory->getImageUrl();?>" width="110"/>
                        </a>
                        <div class="product-shop">
                            <a href="<?php echo $featuredCategory->getUrl();?>">
                                <h1 class="product-name"style="font-size:<?php echo $this->getCustomStyle('link_font_size');?>px;color:#<?php echo $this->getCustomStyle('link_color');?>;">
                                    <?php echo $featuredCategory->getName();?>
                                </h1>
                            </a>
                            <?php //echo Mage::getBlockSingleton('catalog/product')->getPriceHtml($featuredProduct, true)?>
                            <button class="button" onclick="window.location.href = '<?php echo $featuredCategory->getUrl();?>'"><?php echo $this->__('View Detail');?></button>
                        </div>
                    </li>
                    <?php if($max == 2) break;?>
                    <?php endforeach;?>
                </ul>
            </li>
            <?php endif;?>
			<div class="footer-megamenu" style="color:#<?php echo $this->getCustomStyle('text_color'); ?>;font-size:<?php echo $this->getCustomStyle('text_font_size'); ?>px;">
            <?php echo $this->getTemplateBlock($this->getFooterContent()) ?>
        </div>
        </ul>
        
    </div>
<?php endif; ?>
<?php
$_template_map = '<div class="product-list">';
$_template_map .= '<div class="layout-nav">';
$_template_map .= '</div>';
$_template_map .='<div id ="layout_header">';
$_template_map .= '<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#toggleheader">';
$_template_map .='<span>Header Content</span>';
$_template_map .='</a><div>&nbsp;</div></div>';
$_template_map .='<div id="layout_main_content">';
$_template_map .='<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#megamenu_maincontent">';
$_template_map .='<span>Main Content</span>';
$_template_map .='</a><div>&nbsp;</div></div>';
$_template_map .='<div id="layout_feature">';
$_template_map .= '<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#megamenu_featuredcategories">';
$_template_map .='<span>Featured Content</span>';
$_template_map .='</a><div>&nbsp;</div></div>';
$_template_map .='<div id="layout_footer">';
$_template_map .='<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#togglefooter">';
$_template_map .='<span>Footer Content</span>';
$_template_map .='</a><div>&nbsp;</div></div></div>';
?>
<?php
$header = '';
$footer = '';
$this->setDefaultHeaderFooter($header, $footer);
$this->setDefaultGeneralStyle('#ffffff', '#D5D5D5', 1); // (background_color, border_color,border_size)
$this->setDefaultTitleStyle('#ffffff', '#000000', 'Arial,Helmet,Freesans,sans-serif',11); // (title_color, title_background_color, title_font, title_font_size)
$this->setDefaultSubtitleStyle('#000000', 'Arial,Helmet,Freesans,sans-serif', 11); // (subtitle_color, subtitle_font, subtitle_font_size)
$this->setDefaultLinkStyle('#666666', '#3f58a3', 'Arial,Helmet,Freesans,sans-serif', 11); // (link_color, hover_color, link_font, link_font_size)
$this->setDefaultTextStyle('#666666', 'Arial,Helmet,Freesans,sans-serif', 11); // (text_color, text_font, text_font_size)
$this->setDefaultContentGeneral(600,4,180);// megamenu_size,column_number,column_size
/* add title */
$this->addTitle('Categories');
/* add map */
$this->setTemplateMap($_template_map);
$this->setTemplateFileName('product_listing_02');
?>
