<?php $_product = $this->getProduct(); ?>
<?php if($_product->getTypeId() == "configurable" && Mage::getStoreConfig('color_selector_plus/colorselectorplusgeneral/showonlist', Mage::app()->getStore())): ?>
	<?php if($this->getCurrentColor()): ?>
  	    <?php $_attributes = $_product->getTypeInstance(true)->getConfigurableAttributesAsArray($_product); ?>

     	    <?php if(sizeof($_attributes)): ?>
                <?php $productId = $_product->getId(); ?>
                <?php foreach($_attributes as $_attribute): ?>
                    <?php $colorId = $this->colorbyfilter($this->getCurrentColor(),$_attribute['values']); ?>
		    <?php $product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
                    <?php $product_base = $this->decodeImagesForList($product); ?>
		    <?php echo $product_image = Mage::helper('colorselectorplus')->findColorImage($colorId,$product_base,'color', 'image');//returns url for base image ?>
                <?php endforeach; ?>
    	    <?php endif; ?>

        <?php endif; ?>
<?php endif; ?>
<?php $_product = $this->getProduct(); ?>
<?php if($_product->getTypeId() == "configurable" && Mage::getStoreConfig('color_selector_plus/colorselectorplusgeneral/showonlist', Mage::app()->getStore())): ?>

<?php endif; ?>