<?php
$columnNumber = $this->getColumnNumber();
$colunnSize = $this->getColumnSize();
$featuredWidth = 0;
if ($this->hasFeaturedProducts()) {
    $columnNumber = $columnNumber - 1;
    $featuredWidth = 220 + 10;
    $featuredProduct = $this->getOneFeaturedProduct();
} elseif ($this->hasFeaturedCategories()) {
    $columnNumber = $columnNumber - 1;
    $featuredWidth = 220 + 10;
    $featuredCategory = $this->getOneFeaturedCategory();
}
$size = '100% !important';
if(count($this->getParentCategories()) < $columnNumber){
    $columnNumber = count($this->getParentCategories());
}
if ($columnNumber && $colunnSize){
        $size = floatval($columnNumber * $colunnSize + $featuredWidth + ($columnNumber - 1)) . 'px !important';
}
$i = 0;
?>
<div class="grid-categories-megamenu sub-menu" style="border:<?php echo $this->getCustomStyle('border_size') ?>px solid #<?php echo $this->getCustomStyle('border_color') ?>;background:#<?php echo $this->getCustomStyle('background_color') ?> !important;width: <?php echo $size; ?>;" >
<?php if (count($this->getCategories())): ?>
        <ul class="level0-megamenu" id="grid-categories">
            <li class="block-title" style="color:#<?php echo $this->getCustomStyle('text_color'); ?>;font-size:<?php echo $this->getCustomStyle('text_font_size'); ?>px;">			
			<?php
				$text = $this->getTemplateBlock($this->getHeaderContent());
				$newtext = $this->limitString($text , 200 );
				echo $newtext ; 				
				?>
            </li>
                <?php foreach ($this->getParentCategories() as $category): ?>
                <?php if($category->hasChildren()):?>
                <?php $children = $this->getChildrenCollection($category); ?>
                <?php $i++; ?>
                <li class="level1-megamenu" style="<?php if ($colunnSize) echo 'width:' . $colunnSize . 'px !important'; ?>;<?php if ($i == $columnNumber && !$this->hasFeaturedItem()): ?>border-right:none !important<?php endif; ?>">
                    <div class="level1-title">
                        <a href="<?php echo $category->getUrl(); ?>">
							<span style="color:#<?php echo $this->getCustomStyle('subtitle_color'); ?>;font-size:<?php echo $this->getCustomStyle('subtitle_font_size'); ?>px;">
								<?php echo $category->getName() ?>
							</span>	
						</a>
                        

                    </div>
                    <ol class="level2-megamenu" >
						<?php if (count($children)): ?>
                            <?php foreach ($children as $child): ?>
                                <li>
                                    <a style="color:#<?php echo $this->getCustomStyle('link_color'); ?> !important;font-size:<?php echo $this->getCustomStyle('link_font_size'); ?>px !important;" href="<?php echo $child->getUrl(); ?>">
                                        <span><?php echo $child->getName() ?></span>
                                    </a>
                                </li>
							<?php endforeach; ?>
                        <?php endif; ?>
                    </ol>
                </li>
        <?php
        if ($i == $columnNumber){
                    break;
        }
        ?>
        <?php endif;?>
    <?php endforeach; ?>
                
    <?php if ($this->hasFeaturedProducts() && $featuredProduct->getId()): ?>
                <li class="level1-megamenu featured" style="<?php echo 'width:220px !important'; ?>">
                    <div class="level1-title">
                        <span style="color:#<?php echo $this->getCustomStyle('subtitle_color'); ?>;font-size:<?php echo $this->getCustomStyle('subtitle_font_size'); ?>px;"><?php echo $this->__('Featured Product') ?></span>
                        
                    </div>
                    <div class="level1-content">
                        <a class="product-image" href="<?php echo $featuredProduct->getProductUrl(); ?>">
                            <img title="<?php echo Mage::helper('megamenu')->htmlEscape($featuredProduct->getName()); ?>"src="<?php echo $this->getImagePath($featuredProduct, 110);?>" width="110"/>
                        </a>
                        <div class="product-shop">
                            <a href="<?php echo $featuredProduct->getProductUrl(); ?>">
                                <span class="product-name" style="font-size:<?php echo $this->getCustomStyle('link_font_size'); ?>px;color:#<?php echo $this->getCustomStyle('link_color'); ?>;"><?php echo $featuredProduct->getName(); ?></span>
                            </a>
        <?php echo Mage::getBlockSingleton('catalog/product')->setArea('frontend')->getPriceHtml($featuredProduct, true) ?>
                            <button class="button" onclick="window.location.href = '<?php echo $featuredProduct->getProductUrl(); ?>'"><?php echo $this->__('View Detail') ?></button>
                        </div>
                    </div>
                </li>
    <?php elseif ($this->hasFeaturedCategories() && $featuredCategory->getId()): ?>
                <li class="level1-megamenu featured" style="<?php echo 'width:220px !important'; ?>">
                    <div class="level1-title">
                        <span style="color:#<?php echo $this->getCustomStyle('subtitle_color'); ?>;font-size:<?php echo $this->getCustomStyle('subtitle_font_size'); ?>px;"><?php echo $this->__('Featured Category') ?></span>
                        
                    </div>
                    <div class="level1-content">
                        <a class="product-image" href="<?php echo $featuredCategory->getUrl(); ?>">
                            <img title="<?php echo Mage::helper('megamenu')->htmlEscape($featuredCategory->getName()); ?>"src="<?php echo $featuredCategory->getImageUrl(); ?>" width="110"/>
                        </a>
                        <div class="product-shop">
                            <a href="<?php echo $featuredCategory->getUrl(); ?>">
                                <span class="product-name" style="font-size:<?php echo $this->getCustomStyle('link_font_size'); ?>px;color:#<?php echo $this->getCustomStyle('link_color'); ?>;"><?php echo $featuredCategory->getName(); ?></span>
                            </a>
        <?php //echo Mage::getBlockSingleton('catalog/product')->getPriceHtml($featuredProduct, true) ?>
                            <button class="button" onclick="window.location.href = '<?php echo $featuredCategory->getUrl(); ?>'"><?php echo $this->__('View Detail') ?></button>
                        </div>
                    </div>
                </li>
        <?php endif; ?>
        <li class="footer-megamenu" style="color:#<?php echo $this->getCustomStyle('text_color'); ?>;font-size:<?php echo $this->getCustomStyle('text_font_size'); ?>px;">
            <?php echo $this->getTemplateBlock($this->getFooterContent()) ?>
        </li>
        </ul>
<?php endif; ?>
</div>
<?php
$_template_map = '<div class="template-category">';
$_template_map .= '<div class="layout-nav">';
$_template_map .= '</div>';
$_template_map .='<div id ="layout_header">';
$_template_map .= '<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#toggleheader">';
$_template_map .='<span>Header Content</span>';
$_template_map .='</a><div>&nbsp;</div></div>';
$_template_map .='<div id="layout_main_content">';
$_template_map .='<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#megamenu_maincontent">';
$_template_map .='<span>Main Content</span>';
$_template_map .='</a><div>&nbsp;</div></div>';
$_template_map .='<div id="layout_feature">';
$_template_map .= '<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#megamenu_featuredcategories">';
$_template_map .='<span>Featured Content</span>';
$_template_map .='</a><div>&nbsp;</div></div>';
$_template_map .='<div id="layout_footer">';
$_template_map .='<a onmouseover="hoveronLayout(this)" onmouseout="hoveroutLayout(this)" href="#togglefooter">';
$_template_map .='<span>Footer Content</span>';
$_template_map .='</a><div>&nbsp;</div></div></div>';
?>
<?php
$header = 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.';
$footer = '';
$this->setDefaultHeaderFooter($header, $footer);
$this->setDefaultGeneralStyle('#ffffff', '#D5D5D5', 1); // (background_color, border_color,border_size)
$this->setDefaultTitleStyle('#ffffff', '#000000', 'Arial,Helmet,Freesans,sans-serif','11'); // (title_color, title_background_color, title_font, title_font_size)
$this->setDefaultSubtitleStyle('#000000', 'Arial,Helmet,Freesans,sans-serif', 11); // (subtitle_color, subtitle_font, subtitle_font_size)
$this->setDefaultLinkStyle('#666666', '#3f58a3', 'Arial,Helmet,Freesans,sans-serif', 11); // (link_color, hover_color, link_font, link_font_size)
$this->setDefaultTextStyle('#666666', 'Arial,Helmet,Freesans,sans-serif', 11); // (text_color, text_font, text_font_size)
$this->setDefaultContentGeneral(600,4,180);// megamenu_size,column_number,column_size
/* add title */
$this->addTitle('Categories');
/* add map */
$this->setTemplateMap($_template_map);
$this->setTemplateFileName('category_listing_01');
?>
